name: build docker image

on:
  workflow_run:
    workflows: [run-test]
    type: [completed]

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Build Docker image
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Ship to Docker Hub
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: profileorg/profile-be