name: Ship to dockerhub

on:
  push:
    branches: [ "main" ]
jobs:
  ship:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Build Docker image
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Ship to Docker Hub
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: profileorg/profile-be